version: '3.8'

services:
  back_end:
    build: ./back_end
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  web_client:
    build: ./front_end
    ports:
      - "3000:3000"

  mongodb:
      container_name: mongodb
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: Ed3siyi3
        MONGO_INITDB_DATABASE: library
      ports:
        - 27017:27017
      volumes:
        - ./mongo-data:/data/db


  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ed3siyi3
    depends_on:
      - mongodb
    ports:
      - "3300:8081"
    restart: always